name: Build Gestionale Gitemania for Windows

on:
  workflow_dispatch: # Permette di avviare la compilazione manualmente

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --name "GestionaleGitemania" gestionale_gitemania.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: GestionaleGitemania-Windows
        path: dist/GestionaleGitemania.exe
